using Microsoft.EntityFrameworkCore;
using Shared.DbModels;

namespace DataBase
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {

        }

        public DbSet<QuestionModel> Questions { get; set; }
        public DbSet<AnswerModel> Answers { get; set; }
        public DbSet<MetaTagModel> MetaTags { get; set; }
        public DbSet<QuizModel> Quizzes { get; set; }
        public DbSet<EmailModel> Emails { get; set; }
        public DbSet<QuizQuestion> QuizQuestions { get; set; }
        public DbSet<QuestionMetaTag> QuestionMetaTags { get; set; }
        public DbSet<TicketModel> Tickets { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Configure many-to-many relationship for QuizQuestion
            modelBuilder.Entity<QuizQuestion>()
                .HasKey(qq => new { qq.QuizId, qq.QuestionId });

            modelBuilder.Entity<QuizQuestion>()
                .HasOne(qq => qq.Quiz)
                .WithMany(q => q.QuizQuestions)
                .HasForeignKey(qq => qq.QuizId);

            modelBuilder.Entity<QuizQuestion>()
                .HasOne(qq => qq.Question)
                .WithMany(q => q.QuizQuestions)
                .HasForeignKey(qq => qq.QuestionId);

            // Configure many-to-many relationship for QuestionMetaTag
            modelBuilder.Entity<QuestionMetaTag>()
                .HasKey(qmt => new { qmt.QuestionId, qmt.MetaTagId });

            modelBuilder.Entity<QuestionMetaTag>()
                .HasOne(qmt => qmt.Question)
                .WithMany(q => q.QuestionMetaTags)
                .HasForeignKey(qmt => qmt.QuestionId);

            modelBuilder.Entity<QuestionMetaTag>()
                .HasOne(qmt => qmt.MetaTag)
                .WithMany(mt => mt.QuestionMetaTags)
                .HasForeignKey(qmt => qmt.MetaTagId);

            // Configure the relationship between QuestionModel and AnswerModel
            modelBuilder.Entity<AnswerModel>()
                .HasOne(a => a.QuestionModel)
                .WithMany(q => q.Answers)
                .HasForeignKey(a => a.QuestionId)
                .OnDelete(DeleteBehavior.Cascade);


            // Seed Meta Tags
            modelBuilder.Entity<MetaTagModel>().HasData(
                new MetaTagModel { MetaTagId = 1, TagName = "World of Warcraft" },
                new MetaTagModel { MetaTagId = 2, TagName = "League of Legends" },
                new MetaTagModel { MetaTagId = 3, TagName = "Pokemon" },
                new MetaTagModel { MetaTagId = 4, TagName = "Counter-Strike" },
                new MetaTagModel { MetaTagId = 5, TagName = "Super Mario" },
                new MetaTagModel { MetaTagId = 6, TagName = "The Legend of Zelda" }
            );

            // Quizzes
            modelBuilder.Entity<QuizModel>().HasData(
             new QuizModel { QuizId = 1, QuizName = "World of Warcraft Quiz" },
             new QuizModel { QuizId = 2, QuizName = "League of Legends Quiz" },
             new QuizModel { QuizId = 3, QuizName = "Pokemon Quiz" },
             new QuizModel { QuizId = 4, QuizName = "Counter-Strike Quiz" },
             new QuizModel { QuizId = 5, QuizName = "Super Mario Quiz" },
             new QuizModel { QuizId = 6, QuizName = "The Legend of Zelda Quiz" },
             new QuizModel { QuizId = 7, QuizName = "Mixed Game Quiz" }
);

            // Questions
            modelBuilder.Entity<QuestionModel>().HasData(
                // World of Warcraft Questions
                new QuestionModel { QuestionId = 1, Question = "What is the capital city of the Horde?" },
                new QuestionModel { QuestionId = 2, Question = "Who is the Warchief after Thrall?" },
                new QuestionModel { QuestionId = 3, Question = "What class was introduced in 'The Burning Crusade'?" },
                new QuestionModel { QuestionId = 4, Question = "Which expansion featured the continent of Pandaria?" },
                new QuestionModel { QuestionId = 5, Question = "What is the name of the Lich King's sword?" },
                new QuestionModel { QuestionId = 6, Question = "Who guards the Caverns of Time?" },
                new QuestionModel { QuestionId = 7, Question = "Which race can choose to be either Horde or Alliance?" },
                new QuestionModel { QuestionId = 8, Question = "What material is needed to craft a Thunderfury?" },
                new QuestionModel { QuestionId = 9, Question = "Who did players fight in the Firelands raid?" },
                new QuestionModel { QuestionId = 10, Question = "Which dragon aspect is responsible for the Emerald Dream?" },
                new QuestionModel { QuestionId = 11, Question = "What was the first battleground introduced in WoW?" },
                new QuestionModel { QuestionId = 12, Question = "Which raid includes the fight against Illidan?" },
                new QuestionModel { QuestionId = 13, Question = "What profession deals with glyphs?" },
                new QuestionModel { QuestionId = 14, Question = "Where is the Dark Portal located?" },
                new QuestionModel { QuestionId = 15, Question = "What is the home planet of the Draenei?" },

                // League of Legends Questions
                new QuestionModel { QuestionId = 16, Question = "Which champion has an ability called 'Cataclysm'?" },
                new QuestionModel { QuestionId = 17, Question = "What is the main currency in League of Legends?" },
                new QuestionModel { QuestionId = 18, Question = "Which role typically goes to the mid lane?" },
                new QuestionModel { QuestionId = 19, Question = "What is the maximum cooldown reduction achievable?" },
                new QuestionModel { QuestionId = 20, Question = "Who is known as the Grandmaster at Arms?" },
                new QuestionModel { QuestionId = 21, Question = "Which champion is a void creature?" },
                new QuestionModel { QuestionId = 22, Question = "What champion has a pet named Valor?" },
                new QuestionModel { QuestionId = 23, Question = "Which champion can steal abilities?" },
                new QuestionModel { QuestionId = 24, Question = "What item increases attack speed and critical strike chance?" },
                new QuestionModel { QuestionId = 25, Question = "What champion has the ultimate 'Glacial Prison'?" },
                new QuestionModel { QuestionId = 26, Question = "Which map is played in ARAM mode?" },
                new QuestionModel { QuestionId = 27, Question = "What passive effect does the Elder Dragon grant?" },
                new QuestionModel { QuestionId = 28, Question = "Which champion is not associated with Demacia?" },
                new QuestionModel { QuestionId = 29, Question = "What ability is common to all champions?" },
                new QuestionModel { QuestionId = 30, Question = "Which champion was once a prince?" },

                // Pokemon Questions
                new QuestionModel { QuestionId = 31, Question = "Which item evolves Pikachu into Raichu?" },
                new QuestionModel { QuestionId = 32, Question = "Who is the leader of Team Rocket?" },
                new QuestionModel { QuestionId = 33, Question = "Which Pokemon does not evolve?" },
                new QuestionModel { QuestionId = 34, Question = "What type is Mewtwo?" },
                new QuestionModel { QuestionId = 35, Question = "What does TM stand for?" },
                new QuestionModel { QuestionId = 36, Question = "What is the effect of the move 'Splash'?" },
                new QuestionModel { QuestionId = 37, Question = "Who gives you your first Pokemon in Red and Blue?" },
                new QuestionModel { QuestionId = 38, Question = "Which Pokemon is known as the mascot of the series?" },
                new QuestionModel { QuestionId = 39, Question = "What type is effective against Ghost type?" },
                new QuestionModel { QuestionId = 40, Question = "Which legendary bird is an Ice type?" },
                new QuestionModel { QuestionId = 41, Question = "What is unique about the Unown Pokemon?" },
                new QuestionModel { QuestionId = 42, Question = "What is the main goal of the Pokemon games?" },
                new QuestionModel { QuestionId = 43, Question = "Which item is necessary to evolve Onix into Steelix?" },
                new QuestionModel { QuestionId = 44, Question = "What type of move is 'Hyper Beam'?" },
                new QuestionModel { QuestionId = 45, Question = "What is Pikachu's primary type?" },

                // Counter-Strike Questions
                new QuestionModel { QuestionId = 46, Question = "What is the command to buy an AK-47 in the console?" },
                new QuestionModel { QuestionId = 47, Question = "Which map has a bombsite in an Atrium?" },
                new QuestionModel { QuestionId = 48, Question = "What is the maximum number of players on a competitive team?" },
                new QuestionModel { QuestionId = 49, Question = "Which gun is known for being the most accurate?" },
                new QuestionModel { QuestionId = 50, Question = "What does the term 'eco' mean in gameplay?" },
                new QuestionModel { QuestionId = 51, Question = "What is the function of a flashbang?" },
                new QuestionModel { QuestionId = 52, Question = "Which map features a rescue mission?" },
                new QuestionModel { QuestionId = 53, Question = "What is the default pistol for Terrorists?" },
                new QuestionModel { QuestionId = 54, Question = "What weapon is commonly referred to as the 'noob cannon'?" },
                new QuestionModel { QuestionId = 55, Question = "Which grenade is most effective against armored opponents?" },
                new QuestionModel { QuestionId = 56, Question = "What map is known for its long sightlines and sniper battles?" },
                new QuestionModel { QuestionId = 57, Question = "Which CS:GO operation introduced player skins?" },
                new QuestionModel { QuestionId = 58, Question = "What is a 'smurf' in CS:GO?" },
                new QuestionModel { QuestionId = 59, Question = "Which weapon has a 'burst' fire mode?" },
                new QuestionModel { QuestionId = 60, Question = "What does 'B site' refer to?" },

                // Super Mario Questions
                new QuestionModel { QuestionId = 61, Question = "Which game first introduced Yoshi?" },
                new QuestionModel { QuestionId = 62, Question = "What power-up causes Mario to grow larger?" },
                new QuestionModel { QuestionId = 63, Question = "What is the primary antagonist's name in most Mario games?" },
                new QuestionModel { QuestionId = 64, Question = "Which game is set in Dinosaur Land?" },
                new QuestionModel { QuestionId = 65, Question = "What character is Mario's brother?" },
                new QuestionModel { QuestionId = 66, Question = "In which game does Mario first encounter the character Wario?" },
                new QuestionModel { QuestionId = 67, Question = "What kingdom does Peach rule over?" },
                new QuestionModel { QuestionId = 68, Question = "What color are Mario's overalls?" },
                new QuestionModel { QuestionId = 69, Question = "Which game did Mario first appear in?" },
                new QuestionModel { QuestionId = 70, Question = "What vehicle does Mario use in Mario Kart?" },
                new QuestionModel { QuestionId = 71, Question = "What is the name of Mario's dinosaur friend?" },
                new QuestionModel { QuestionId = 72, Question = "Which game introduces Mario's flying raccoon suit?" },
                new QuestionModel { QuestionId = 73, Question = "What fruit does Yoshi eat to gain power-ups?" },
                new QuestionModel { QuestionId = 74, Question = "Which game features Mario as a plumber?" },
                new QuestionModel { QuestionId = 75, Question = "Who is Mario's usual nemesis in the Donkey Kong series?" },

                // The Legend of Zelda Questions
                new QuestionModel { QuestionId = 76, Question = "What is the name of Link's green cap?" },
                new QuestionModel { QuestionId = 77, Question = "Which game involves traveling between two parallel worlds?" },
                new QuestionModel { QuestionId = 78, Question = "Who teaches Link the 'Spin Attack'?" },
                new QuestionModel { QuestionId = 79, Question = "What is Zelda's alter ego in 'Ocarina of Time'?" },
                new QuestionModel { QuestionId = 80, Question = "What weapon is most effective against Ganon?" },
                new QuestionModel { QuestionId = 81, Question = "What instrument does Link play in 'The Wind Waker'?" },
                new QuestionModel { QuestionId = 82, Question = "Which Zelda game is set on an island?" },
                new QuestionModel { QuestionId = 83, Question = "Who is the creator of The Legend of Zelda series?" },
                new QuestionModel { QuestionId = 84, Question = "What is the Triforce?" },
                new QuestionModel { QuestionId = 85, Question = "Which item allows Link to travel through time in 'Ocarina of Time'?" },
                new QuestionModel { QuestionId = 86, Question = "Who kidnaps Zelda in the original 'Legend of Zelda' game?" },
                new QuestionModel { QuestionId = 87, Question = "What unique ability does Link have in 'Majora's Mask'?" },
                new QuestionModel { QuestionId = 88, Question = "What color is the tunic Link wears by default?" },
                new QuestionModel { QuestionId = 89, Question = "Which game did Link first appear in on the Nintendo Entertainment System?" },
                new QuestionModel { QuestionId = 90, Question = "What is the name of the magical sword Link often uses?" }
            );

            // Answers
            modelBuilder.Entity<AnswerModel>().HasData(
                // World of Warcraft Answers
                new AnswerModel { AnswerId = 1, QuestionId = 1, IsCorrect = true, Answer = "Orgrimmar" },
                new AnswerModel { AnswerId = 2, QuestionId = 1, IsCorrect = false, Answer = "Undercity" },
                new AnswerModel { AnswerId = 3, QuestionId = 1, IsCorrect = false, Answer = "Thunder Bluff" },
                new AnswerModel { AnswerId = 4, QuestionId = 1, IsCorrect = false, Answer = "Silvermoon" },
                new AnswerModel { AnswerId = 5, QuestionId = 2, IsCorrect = true, Answer = "Garrosh Hellscream" },
                new AnswerModel { AnswerId = 6, QuestionId = 2, IsCorrect = false, Answer = "Vol'jin" },
                new AnswerModel { AnswerId = 7, QuestionId = 2, IsCorrect = false, Answer = "Sylvanas Windrunner" },
                new AnswerModel { AnswerId = 8, QuestionId = 2, IsCorrect = false, Answer = "Baine Bloodhoof" },
                new AnswerModel { AnswerId = 9, QuestionId = 3, IsCorrect = true, Answer = "Blood Elf" },
                new AnswerModel { AnswerId = 10, QuestionId = 3, IsCorrect = false, Answer = "Night Elf" },
                new AnswerModel { AnswerId = 11, QuestionId = 3, IsCorrect = false, Answer = "Draenei" },
                new AnswerModel { AnswerId = 12, QuestionId = 3, IsCorrect = false, Answer = "Goblin" },
                new AnswerModel { AnswerId = 13, QuestionId = 4, IsCorrect = true, Answer = "Mists of Pandaria" },
                new AnswerModel { AnswerId = 14, QuestionId = 4, IsCorrect = false, Answer = "Warlords of Draenor" },
                new AnswerModel { AnswerId = 15, QuestionId = 4, IsCorrect = false, Answer = "Legion" },
                new AnswerModel { AnswerId = 16, QuestionId = 4, IsCorrect = false, Answer = "Battle for Azeroth" },
                new AnswerModel { AnswerId = 17, QuestionId = 5, IsCorrect = true, Answer = "Frostmourne" },
                new AnswerModel { AnswerId = 18, QuestionId = 5, IsCorrect = false, Answer = "Ashbringer" },
                new AnswerModel { AnswerId = 19, QuestionId = 5, IsCorrect = false, Answer = "Doomhammer" },
                new AnswerModel { AnswerId = 20, QuestionId = 5, IsCorrect = false, Answer = "Shadowmourne" },
                new AnswerModel { AnswerId = 21, QuestionId = 6, IsCorrect = true, Answer = "Nozdormu" },
                new AnswerModel { AnswerId = 22, QuestionId = 6, IsCorrect = false, Answer = "Ysera" },
                new AnswerModel { AnswerId = 23, QuestionId = 6, IsCorrect = false, Answer = "Malygos" },
                new AnswerModel { AnswerId = 24, QuestionId = 6, IsCorrect = false, Answer = "Kalecgos" },
                new AnswerModel { AnswerId = 25, QuestionId = 7, IsCorrect = true, Answer = "Pandaren" },
                new AnswerModel { AnswerId = 26, QuestionId = 7, IsCorrect = false, Answer = "Troll" },
                new AnswerModel { AnswerId = 27, QuestionId = 7, IsCorrect = false, Answer = "Tauren" },
                new AnswerModel { AnswerId = 28, QuestionId = 7, IsCorrect = false, Answer = "Forsaken" },
                new AnswerModel { AnswerId = 29, QuestionId = 8, IsCorrect = true, Answer = "Elementium" },
                new AnswerModel { AnswerId = 30, QuestionId = 8, IsCorrect = false, Answer = "Saronite" },
                new AnswerModel { AnswerId = 31, QuestionId = 8, IsCorrect = false, Answer = "Thorium" },
                new AnswerModel { AnswerId = 32, QuestionId = 8, IsCorrect = false, Answer = "Titansteel" },
                new AnswerModel { AnswerId = 33, QuestionId = 9, IsCorrect = true, Answer = "Ragnaros" },
                new AnswerModel { AnswerId = 34, QuestionId = 9, IsCorrect = false, Answer = "Al'Akir" },
                new AnswerModel { AnswerId = 35, QuestionId = 9, IsCorrect = false, Answer = "Nefarian" },
                new AnswerModel { AnswerId = 36, QuestionId = 9, IsCorrect = false, Answer = "Cho'gall" },
                new AnswerModel { AnswerId = 37, QuestionId = 10, IsCorrect = true, Answer = "Ysera" },
                new AnswerModel { AnswerId = 38, QuestionId = 10, IsCorrect = false, Answer = "Alexstrasza" },
                new AnswerModel { AnswerId = 39, QuestionId = 10, IsCorrect = false, Answer = "Neltharion" },
                new AnswerModel { AnswerId = 40, QuestionId = 10, IsCorrect = false, Answer = "Khadgar" },
                new AnswerModel { AnswerId = 41, QuestionId = 11, IsCorrect = true, Answer = "Warsong Gulch" },
                new AnswerModel { AnswerId = 42, QuestionId = 11, IsCorrect = false, Answer = "Arathi Basin" },
                new AnswerModel { AnswerId = 43, QuestionId = 11, IsCorrect = false, Answer = "Alterac Valley" },
                new AnswerModel { AnswerId = 44, QuestionId = 11, IsCorrect = false, Answer = "Eye of the Storm" },
                new AnswerModel { AnswerId = 45, QuestionId = 12, IsCorrect = true, Answer = "Black Temple" },
                new AnswerModel { AnswerId = 46, QuestionId = 12, IsCorrect = false, Answer = "Sunwell Plateau" },
                new AnswerModel { AnswerId = 47, QuestionId = 12, IsCorrect = false, Answer = "Karazhan" },
                new AnswerModel { AnswerId = 48, QuestionId = 12, IsCorrect = false, Answer = "Naxxramas" },
                new AnswerModel { AnswerId = 49, QuestionId = 13, IsCorrect = true, Answer = "Inscription" },
                new AnswerModel { AnswerId = 50, QuestionId = 13, IsCorrect = false, Answer = "Herbalism" },
                new AnswerModel { AnswerId = 51, QuestionId = 13, IsCorrect = false, Answer = "Alchemy" },
                new AnswerModel { AnswerId = 52, QuestionId = 13, IsCorrect = false, Answer = "Jewelcrafting" },
                new AnswerModel { AnswerId = 53, QuestionId = 14, IsCorrect = true, Answer = "Blasted Lands" },
                new AnswerModel { AnswerId = 54, QuestionId = 14, IsCorrect = false, Answer = "Hellfire Peninsula" },
                new AnswerModel { AnswerId = 55, QuestionId = 14, IsCorrect = false, Answer = "Shadowmoon Valley" },
                new AnswerModel { AnswerId = 56, QuestionId = 14, IsCorrect = false, Answer = "Tanaan Jungle" },
                new AnswerModel { AnswerId = 57, QuestionId = 15, IsCorrect = true, Answer = "Argus" },
                new AnswerModel { AnswerId = 58, QuestionId = 15, IsCorrect = false, Answer = "Draenor" },
                new AnswerModel { AnswerId = 59, QuestionId = 15, IsCorrect = false, Answer = "Azeroth" },
                new AnswerModel { AnswerId = 60, QuestionId = 15, IsCorrect = false, Answer = "Outland" },

                // League of Legends Answers
                new AnswerModel { AnswerId = 61, QuestionId = 16, IsCorrect = true, Answer = "Jarvan IV" },
                new AnswerModel { AnswerId = 62, QuestionId = 16, IsCorrect = false, Answer = "Garen" },
                new AnswerModel { AnswerId = 63, QuestionId = 16, IsCorrect = false, Answer = "Darius" },
                new AnswerModel { AnswerId = 64, QuestionId = 16, IsCorrect = false, Answer = "Xin Zhao" },
                new AnswerModel { AnswerId = 65, QuestionId = 17, IsCorrect = true, Answer = "Blue Essence" },
                new AnswerModel { AnswerId = 66, QuestionId = 17, IsCorrect = false, Answer = "Riot Points" },
                new AnswerModel { AnswerId = 67, QuestionId = 17, IsCorrect = false, Answer = "Gold" },
                new AnswerModel { AnswerId = 68, QuestionId = 17, IsCorrect = false, Answer = "Influence Points" },
                new AnswerModel { AnswerId = 69, QuestionId = 18, IsCorrect = true, Answer = "Mage" },
                new AnswerModel { AnswerId = 70, QuestionId = 18, IsCorrect = false, Answer = "Marksman" },
                new AnswerModel { AnswerId = 71, QuestionId = 18, IsCorrect = false, Answer = "Support" },
                new AnswerModel { AnswerId = 72, QuestionId = 18, IsCorrect = false, Answer = "Tank" },
                new AnswerModel { AnswerId = 73, QuestionId = 19, IsCorrect = true, Answer = "40%" },
                new AnswerModel { AnswerId = 74, QuestionId = 19, IsCorrect = false, Answer = "50%" },
                new AnswerModel { AnswerId = 75, QuestionId = 19, IsCorrect = false, Answer = "35%" },
                new AnswerModel { AnswerId = 76, QuestionId = 19, IsCorrect = false, Answer = "45%" },
                new AnswerModel { AnswerId = 77, QuestionId = 20, IsCorrect = true, Answer = "Jax" },
                new AnswerModel { AnswerId = 78, QuestionId = 20, IsCorrect = false, Answer = "Jayce" },
                new AnswerModel { AnswerId = 79, QuestionId = 20, IsCorrect = false, Answer = "Tryndamere" },
                new AnswerModel { AnswerId = 80, QuestionId = 20, IsCorrect = false, Answer = "Fiora" },
                new AnswerModel { AnswerId = 81, QuestionId = 21, IsCorrect = true, Answer = "Kha'Zix" },
                new AnswerModel { AnswerId = 82, QuestionId = 21, IsCorrect = false, Answer = "Rengar" },
                new AnswerModel { AnswerId = 83, QuestionId = 21, IsCorrect = false, Answer = "Vel'Koz" },
                new AnswerModel { AnswerId = 84, QuestionId = 21, IsCorrect = false, Answer = "Malzahar" },
                new AnswerModel { AnswerId = 85, QuestionId = 22, IsCorrect = true, Answer = "Quinn" },
                new AnswerModel { AnswerId = 86, QuestionId = 22, IsCorrect = false, Answer = "Caitlyn" },
                new AnswerModel { AnswerId = 87, QuestionId = 22, IsCorrect = false, Answer = "Swain" },
                new AnswerModel { AnswerId = 88, QuestionId = 22, IsCorrect = false, Answer = "Anivia" },
                new AnswerModel { AnswerId = 89, QuestionId = 23, IsCorrect = true, Answer = "Sylas" },
                new AnswerModel { AnswerId = 90, QuestionId = 23, IsCorrect = false, Answer = "Neeko" },
                new AnswerModel { AnswerId = 91, QuestionId = 23, IsCorrect = false, Answer = "Zoe" },
                new AnswerModel { AnswerId = 92, QuestionId = 23, IsCorrect = false, Answer = "Lux" },
                new AnswerModel { AnswerId = 93, QuestionId = 24, IsCorrect = true, Answer = "Phantom Dancer" },
                new AnswerModel { AnswerId = 94, QuestionId = 24, IsCorrect = false, Answer = "Statikk Shiv" },
                new AnswerModel { AnswerId = 95, QuestionId = 24, IsCorrect = false, Answer = "Rapid Firecannon" },
                new AnswerModel { AnswerId = 96, QuestionId = 24, IsCorrect = false, Answer = "Runaan's Hurricane" },
                new AnswerModel { AnswerId = 97, QuestionId = 25, IsCorrect = true, Answer = "Sejuani" },
                new AnswerModel { AnswerId = 98, QuestionId = 25, IsCorrect = false, Answer = "Ashe" },
                new AnswerModel { AnswerId = 99, QuestionId = 25, IsCorrect = false, Answer = "Braum" },
                new AnswerModel { AnswerId = 100, QuestionId = 25, IsCorrect = false, Answer = "Lissandra" },
                new AnswerModel { AnswerId = 101, QuestionId = 26, IsCorrect = true, Answer = "Howling Abyss" },
                new AnswerModel { AnswerId = 102, QuestionId = 26, IsCorrect = false, Answer = "Summoner's Rift" },
                new AnswerModel { AnswerId = 103, QuestionId = 26, IsCorrect = false, Answer = "Twisted Treeline" },
                new AnswerModel { AnswerId = 104, QuestionId = 26, IsCorrect = false, Answer = "Crystal Scar" },
                new AnswerModel { AnswerId = 105, QuestionId = 27, IsCorrect = true, Answer = "Burn damage over time" },
                new AnswerModel { AnswerId = 106, QuestionId = 27, IsCorrect = false, Answer = "Health regeneration" },
                new AnswerModel { AnswerId = 107, QuestionId = 27, IsCorrect = false, Answer = "Increased damage output" },
                new AnswerModel { AnswerId = 108, QuestionId = 27, IsCorrect = false, Answer = "Shield protection" },
                new AnswerModel { AnswerId = 109, QuestionId = 28, IsCorrect = true, Answer = "Lux" },
                new AnswerModel { AnswerId = 110, QuestionId = 28, IsCorrect = false, Answer = "Garen" },
                new AnswerModel { AnswerId = 111, QuestionId = 28, IsCorrect = false, Answer = "Fiora" },
                new AnswerModel { AnswerId = 112, QuestionId = 28, IsCorrect = false, Answer = "Xin Zhao" },
                new AnswerModel { AnswerId = 113, QuestionId = 29, IsCorrect = true, Answer = "Flash" },
                new AnswerModel { AnswerId = 114, QuestionId = 29, IsCorrect = false, Answer = "Heal" },
                new AnswerModel { AnswerId = 115, QuestionId = 29, IsCorrect = false, Answer = "Ghost" },
                new AnswerModel { AnswerId = 116, QuestionId = 29, IsCorrect = false, Answer = "Barrier" },
                new AnswerModel { AnswerId = 117, QuestionId = 30, IsCorrect = true, Answer = "Jarvan IV" },
                new AnswerModel { AnswerId = 118, QuestionId = 30, IsCorrect = false, Answer = "Malzahar" },
                new AnswerModel { AnswerId = 119, QuestionId = 30, IsCorrect = false, Answer = "Azir" },
                new AnswerModel { AnswerId = 120, QuestionId = 30, IsCorrect = false, Answer = "Viktor" },

                // Pokemon Answers
                new AnswerModel { AnswerId = 121, QuestionId = 31, IsCorrect = true, Answer = "Thunder Stone" },
                new AnswerModel { AnswerId = 122, QuestionId = 31, IsCorrect = false, Answer = "Water Stone" },
                new AnswerModel { AnswerId = 123, QuestionId = 31, IsCorrect = false, Answer = "Fire Stone" },
                new AnswerModel { AnswerId = 124, QuestionId = 31, IsCorrect = false, Answer = "Leaf Stone" },
                new AnswerModel { AnswerId = 125, QuestionId = 32, IsCorrect = true, Answer = "Giovanni" },
                new AnswerModel { AnswerId = 126, QuestionId = 32, IsCorrect = false, Answer = "Archer" },
                new AnswerModel { AnswerId = 127, QuestionId = 32, IsCorrect = false, Answer = "Maxie" },
                new AnswerModel { AnswerId = 128, QuestionId = 32, IsCorrect = false, Answer = "Cyrus" },
                new AnswerModel { AnswerId = 129, QuestionId = 33, IsCorrect = true, Answer = "Ditto" },
                new AnswerModel { AnswerId = 130, QuestionId = 33, IsCorrect = false, Answer = "Jigglypuff" },
                new AnswerModel { AnswerId = 131, QuestionId = 33, IsCorrect = false, Answer = "Gyarados" },
                new AnswerModel { AnswerId = 132, QuestionId = 33, IsCorrect = false, Answer = "Eevee" },
                new AnswerModel { AnswerId = 133, QuestionId = 34, IsCorrect = true, Answer = "Psychic" },
                new AnswerModel { AnswerId = 134, QuestionId = 34, IsCorrect = false, Answer = "Dark" },
                new AnswerModel { AnswerId = 135, QuestionId = 34, IsCorrect = false, Answer = "Ghost" },
                new AnswerModel { AnswerId = 136, QuestionId = 34, IsCorrect = false, Answer = "Fighting" },
                new AnswerModel { AnswerId = 137, QuestionId = 35, IsCorrect = true, Answer = "Technical Machine" },
                new AnswerModel { AnswerId = 138, QuestionId = 35, IsCorrect = false, Answer = "Type Modifier" },
                new AnswerModel { AnswerId = 139, QuestionId = 35, IsCorrect = false, Answer = "Trainer's Medallion" },
                new AnswerModel { AnswerId = 140, QuestionId = 35, IsCorrect = false, Answer = "Transformation Module" },
                new AnswerModel { AnswerId = 141, QuestionId = 36, IsCorrect = true, Answer = "No effect" },
                new AnswerModel { AnswerId = 142, QuestionId = 36, IsCorrect = false, Answer = "Small damage" },
                new AnswerModel { AnswerId = 143, QuestionId = 36, IsCorrect = false, Answer = "Stat boost" },
                new AnswerModel { AnswerId = 144, QuestionId = 36, IsCorrect = false, Answer = "Heals a little HP" },
                new AnswerModel { AnswerId = 145, QuestionId = 37, IsCorrect = true, Answer = "Professor Oak" },
                new AnswerModel { AnswerId = 146, QuestionId = 37, IsCorrect = false, Answer = "Professor Elm" },
                new AnswerModel { AnswerId = 147, QuestionId = 37, IsCorrect = false, Answer = "Professor Birch" },
                new AnswerModel { AnswerId = 148, QuestionId = 37, IsCorrect = false, Answer = "Professor Kukui" },
                new AnswerModel { AnswerId = 149, QuestionId = 38, IsCorrect = true, Answer = "Pikachu" },
                new AnswerModel { AnswerId = 150, QuestionId = 38, IsCorrect = false, Answer = "Charizard" },
                new AnswerModel { AnswerId = 151, QuestionId = 38, IsCorrect = false, Answer = "Mewtwo" },
                new AnswerModel { AnswerId = 152, QuestionId = 38, IsCorrect = false, Answer = "Jigglypuff" },
                new AnswerModel { AnswerId = 153, QuestionId = 39, IsCorrect = true, Answer = "Dark" },
                new AnswerModel { AnswerId = 154, QuestionId = 39, IsCorrect = false, Answer = "Psychic" },
                new AnswerModel { AnswerId = 155, QuestionId = 39, IsCorrect = false, Answer = "Normal" },
                new AnswerModel { AnswerId = 156, QuestionId = 39, IsCorrect = false, Answer = "Fighting" },
                new AnswerModel { AnswerId = 157, QuestionId = 40, IsCorrect = true, Answer = "Articuno" },
                new AnswerModel { AnswerId = 158, QuestionId = 40, IsCorrect = false, Answer = "Zapdos" },
                new AnswerModel { AnswerId = 159, QuestionId = 40, IsCorrect = false, Answer = "Moltres" },
                new AnswerModel { AnswerId = 160, QuestionId = 40, IsCorrect = false, Answer = "Ho-Oh" },
                new AnswerModel { AnswerId = 161, QuestionId = 41, IsCorrect = true, Answer = "It has many forms" },
                new AnswerModel { AnswerId = 162, QuestionId = 41, IsCorrect = false, Answer = "It is invisible" },
                new AnswerModel { AnswerId = 163, QuestionId = 41, IsCorrect = false, Answer = "It changes type with weather" },
                new AnswerModel { AnswerId = 164, QuestionId = 41, IsCorrect = false, Answer = "It can breed with any Pokémon" },
                new AnswerModel { AnswerId = 165, QuestionId = 42, IsCorrect = true, Answer = "To become Pokémon Champion" },
                new AnswerModel { AnswerId = 166, QuestionId = 42, IsCorrect = false, Answer = "To complete the Pokédex" },
                new AnswerModel { AnswerId = 167, QuestionId = 42, IsCorrect = false, Answer = "To rescue the professor" },
                new AnswerModel { AnswerId = 168, QuestionId = 42, IsCorrect = false, Answer = "To defeat Team Rocket" },
                new AnswerModel { AnswerId = 169, QuestionId = 43, IsCorrect = true, Answer = "Metal Coat" },
                new AnswerModel { AnswerId = 170, QuestionId = 43, IsCorrect = false, Answer = "Link Cable" },
                new AnswerModel { AnswerId = 171, QuestionId = 43, IsCorrect = false, Answer = "Sun Stone" },
                new AnswerModel { AnswerId = 172, QuestionId = 43, IsCorrect = false, Answer = "Moon Stone" },
                new AnswerModel { AnswerId = 173, QuestionId = 44, IsCorrect = true, Answer = "Normal" },
                new AnswerModel { AnswerId = 174, QuestionId = 44, IsCorrect = false, Answer = "Fighting" },
                new AnswerModel { AnswerId = 175, QuestionId = 44, IsCorrect = false, Answer = "Fire" },
                new AnswerModel { AnswerId = 176, QuestionId = 44, IsCorrect = false, Answer = "Dragon" },
                new AnswerModel { AnswerId = 177, QuestionId = 45, IsCorrect = true, Answer = "Electric" },
                new AnswerModel { AnswerId = 178, QuestionId = 45, IsCorrect = false, Answer = "Steel" },
                new AnswerModel { AnswerId = 179, QuestionId = 45, IsCorrect = false, Answer = "Grass" },
                new AnswerModel { AnswerId = 180, QuestionId = 45, IsCorrect = false, Answer = "Ice" },

                // Counter-Strike Answers
                new AnswerModel { AnswerId = 181, QuestionId = 46, IsCorrect = true, Answer = "buy ak47" },
                new AnswerModel { AnswerId = 182, QuestionId = 46, IsCorrect = false, Answer = "purchase ak47" },
                new AnswerModel { AnswerId = 183, QuestionId = 46, IsCorrect = false, Answer = "get ak47" },
                new AnswerModel { AnswerId = 184, QuestionId = 46, IsCorrect = false, Answer = "ak47" },
                new AnswerModel { AnswerId = 185, QuestionId = 47, IsCorrect = true, Answer = "Italy" },
                new AnswerModel { AnswerId = 186, QuestionId = 47, IsCorrect = false, Answer = "Dust II" },
                new AnswerModel { AnswerId = 187, QuestionId = 47, IsCorrect = false, Answer = "Aztec" },
                new AnswerModel { AnswerId = 188, QuestionId = 47, IsCorrect = false, Answer = "Cobblestone" },
                new AnswerModel { AnswerId = 189, QuestionId = 48, IsCorrect = true, Answer = "5" },
                new AnswerModel { AnswerId = 190, QuestionId = 48, IsCorrect = false, Answer = "6" },
                new AnswerModel { AnswerId = 191, QuestionId = 48, IsCorrect = false, Answer = "4" },
                new AnswerModel { AnswerId = 192, QuestionId = 48, IsCorrect = false, Answer = "7" },
                new AnswerModel { AnswerId = 193, QuestionId = 49, IsCorrect = true, Answer = "AWP" },
                new AnswerModel { AnswerId = 194, QuestionId = 49, IsCorrect = false, Answer = "AK-47" },
                new AnswerModel { AnswerId = 195, QuestionId = 49, IsCorrect = false, Answer = "M4A1" },
                new AnswerModel { AnswerId = 196, QuestionId = 49, IsCorrect = false, Answer = "Glock" },
                new AnswerModel { AnswerId = 197, QuestionId = 50, IsCorrect = true, Answer = "Saving money for future rounds" },
                new AnswerModel { AnswerId = 198, QuestionId = 50, IsCorrect = false, Answer = "Buying the most expensive gear" },
                new AnswerModel { AnswerId = 199, QuestionId = 50, IsCorrect = false, Answer = "Using eco weapons only" },
                new AnswerModel { AnswerId = 200, QuestionId = 50, IsCorrect = false, Answer = "Rushing the opponent quickly" },
                new AnswerModel { AnswerId = 201, QuestionId = 51, IsCorrect = true, Answer = "Blinds opponents temporarily" },
                new AnswerModel { AnswerId = 202, QuestionId = 51, IsCorrect = false, Answer = "Causes damage over time" },
                new AnswerModel { AnswerId = 203, QuestionId = 51, IsCorrect = false, Answer = "Silences footsteps" },
                new AnswerModel { AnswerId = 204, QuestionId = 51, IsCorrect = false, Answer = "Marks enemies on the radar" },
                new AnswerModel { AnswerId = 205, QuestionId = 52, IsCorrect = true, Answer = "Office" },
                new AnswerModel { AnswerId = 206, QuestionId = 52, IsCorrect = false, Answer = "Hostage" },
                new AnswerModel { AnswerId = 207, QuestionId = 52, IsCorrect = false, Answer = "Assault" },
                new AnswerModel { AnswerId = 208, QuestionId = 52, IsCorrect = false, Answer = "Militia" },
                new AnswerModel { AnswerId = 209, QuestionId = 53, IsCorrect = true, Answer = "Glock-18" },
                new AnswerModel { AnswerId = 210, QuestionId = 53, IsCorrect = false, Answer = "USP-S" },
                new AnswerModel { AnswerId = 211, QuestionId = 53, IsCorrect = false, Answer = "P250" },
                new AnswerModel { AnswerId = 212, QuestionId = 53, IsCorrect = false, Answer = "Five-SeveN" },
                new AnswerModel { AnswerId = 213, QuestionId = 54, IsCorrect = true, Answer = "Auto-sniper" },
                new AnswerModel { AnswerId = 214, QuestionId = 54, IsCorrect = false, Answer = "Scout" },
                new AnswerModel { AnswerId = 215, QuestionId = 54, IsCorrect = false, Answer = "AWP" },
                new AnswerModel { AnswerId = 216, QuestionId = 54, IsCorrect = false, Answer = "AK-47" },
                new AnswerModel { AnswerId = 217, QuestionId = 55, IsCorrect = true, Answer = "HE Grenade" },
                new AnswerModel { AnswerId = 218, QuestionId = 55, IsCorrect = false, Answer = "Smoke Grenade" },
                new AnswerModel { AnswerId = 219, QuestionId = 55, IsCorrect = false, Answer = "Flashbang" },
                new AnswerModel { AnswerId = 220, QuestionId = 55, IsCorrect = false, Answer = "Decoy Grenade" },
                new AnswerModel { AnswerId = 221, QuestionId = 56, IsCorrect = true, Answer = "Dust II" },
                new AnswerModel { AnswerId = 222, QuestionId = 56, IsCorrect = false, Answer = "Train" },
                new AnswerModel { AnswerId = 223, QuestionId = 56, IsCorrect = false, Answer = "Overpass" },
                new AnswerModel { AnswerId = 224, QuestionId = 56, IsCorrect = false, Answer = "Cache" },
                new AnswerModel { AnswerId = 225, QuestionId = 57, IsCorrect = true, Answer = "Operation Bravo" },
                new AnswerModel { AnswerId = 226, QuestionId = 57, IsCorrect = false, Answer = "Operation Hydra" },
                new AnswerModel { AnswerId = 227, QuestionId = 57, IsCorrect = false, Answer = "Operation Vanguard" },
                new AnswerModel { AnswerId = 228, QuestionId = 57, IsCorrect = false, Answer = "Operation Bloodhound" },
                new AnswerModel { AnswerId = 229, QuestionId = 58, IsCorrect = true, Answer = "An experienced player who plays in a lower-ranked account" },
                new AnswerModel { AnswerId = 230, QuestionId = 58, IsCorrect = false, Answer = "A new player still learning the game" },
                new AnswerModel { AnswerId = 231, QuestionId = 58, IsCorrect = false, Answer = "A player who frequently disconnects" },
                new AnswerModel { AnswerId = 232, QuestionId = 58, IsCorrect = false, Answer = "A player who cheats" },
                new AnswerModel { AnswerId = 233, QuestionId = 59, IsCorrect = true, Answer = "FAMAS" },
                new AnswerModel { AnswerId = 234, QuestionId = 59, IsCorrect = false, Answer = "M4A1-S" },
                new AnswerModel { AnswerId = 235, QuestionId = 59, IsCorrect = false, Answer = "AK-47" },
                new AnswerModel { AnswerId = 236, QuestionId = 59, IsCorrect = false, Answer = "Glock-18" },
                new AnswerModel { AnswerId = 237, QuestionId = 60, IsCorrect = true, Answer = "A bombsite on a map" },
                new AnswerModel { AnswerId = 238, QuestionId = 60, IsCorrect = false, Answer = "A meeting area in the middle of the map" },
                new AnswerModel { AnswerId = 239, QuestionId = 60, IsCorrect = false, Answer = "A weapon buy zone" },
                new AnswerModel { AnswerId = 240, QuestionId = 60, IsCorrect = false, Answer = "A sniper's nest" },

                // Super Mario Answers
                new AnswerModel { AnswerId = 241, QuestionId = 61, IsCorrect = true, Answer = "Super Mario World" },
                new AnswerModel { AnswerId = 242, QuestionId = 61, IsCorrect = false, Answer = "Super Mario Bros." },
                new AnswerModel { AnswerId = 243, QuestionId = 61, IsCorrect = false, Answer = "Super Mario 64" },
                new AnswerModel { AnswerId = 244, QuestionId = 61, IsCorrect = false, Answer = "Super Mario Sunshine" },
                new AnswerModel { AnswerId = 245, QuestionId = 62, IsCorrect = true, Answer = "Super Mushroom" },
                new AnswerModel { AnswerId = 246, QuestionId = 62, IsCorrect = false, Answer = "Fire Flower" },
                new AnswerModel { AnswerId = 247, QuestionId = 62, IsCorrect = false, Answer = "Starman" },
                new AnswerModel { AnswerId = 248, QuestionId = 62, IsCorrect = false, Answer = "Cape Feather" },
                new AnswerModel { AnswerId = 249, QuestionId = 63, IsCorrect = true, Answer = "Bowser" },
                new AnswerModel { AnswerId = 250, QuestionId = 63, IsCorrect = false, Answer = "Wario" },
                new AnswerModel { AnswerId = 251, QuestionId = 63, IsCorrect = false, Answer = "Donkey Kong" },
                new AnswerModel { AnswerId = 252, QuestionId = 63, IsCorrect = false, Answer = "King Boo" },
                new AnswerModel { AnswerId = 253, QuestionId = 64, IsCorrect = true, Answer = "Super Mario World" },
                new AnswerModel { AnswerId = 254, QuestionId = 64, IsCorrect = false, Answer = "Super Mario Bros. 3" },
                new AnswerModel { AnswerId = 255, QuestionId = 64, IsCorrect = false, Answer = "Super Mario Odyssey" },
                new AnswerModel { AnswerId = 256, QuestionId = 64, IsCorrect = false, Answer = "Super Mario Galaxy" },
                new AnswerModel { AnswerId = 257, QuestionId = 65, IsCorrect = true, Answer = "Luigi" },
                new AnswerModel { AnswerId = 258, QuestionId = 65, IsCorrect = false, Answer = "Peach" },
                new AnswerModel { AnswerId = 259, QuestionId = 65, IsCorrect = false, Answer = "Toad" },
                new AnswerModel { AnswerId = 260, QuestionId = 65, IsCorrect = false, Answer = "Yoshi" },
                new AnswerModel { AnswerId = 261, QuestionId = 66, IsCorrect = true, Answer = "Super Mario Land 2: 6 Golden Coins" },
                new AnswerModel { AnswerId = 262, QuestionId = 66, IsCorrect = false, Answer = "Super Mario Bros." },
                new AnswerModel { AnswerId = 263, QuestionId = 66, IsCorrect = false, Answer = "Super Mario World" },
                new AnswerModel { AnswerId = 264, QuestionId = 66, IsCorrect = false, Answer = "Mario Kart 64" },
                new AnswerModel { AnswerId = 265, QuestionId = 67, IsCorrect = true, Answer = "Mushroom Kingdom" },
                new AnswerModel { AnswerId = 266, QuestionId = 67, IsCorrect = false, Answer = "Dinosaur Land" },
                new AnswerModel { AnswerId = 267, QuestionId = 67, IsCorrect = false, Answer = "Sarasaland" },
                new AnswerModel { AnswerId = 268, QuestionId = 67, IsCorrect = false, Answer = "Isle Delfino" },
                new AnswerModel { AnswerId = 269, QuestionId = 68, IsCorrect = true, Answer = "Blue" },
                new AnswerModel { AnswerId = 270, QuestionId = 68, IsCorrect = false, Answer = "Red" },
                new AnswerModel { AnswerId = 271, QuestionId = 68, IsCorrect = false, Answer = "Green" },
                new AnswerModel { AnswerId = 272, QuestionId = 68, IsCorrect = false, Answer = "Yellow" },
                new AnswerModel { AnswerId = 273, QuestionId = 69, IsCorrect = true, Answer = "Donkey Kong" },
                new AnswerModel { AnswerId = 274, QuestionId = 69, IsCorrect = false, Answer = "Super Mario Bros." },
                new AnswerModel { AnswerId = 275, QuestionId = 69, IsCorrect = false, Answer = "Mario Bros." },
                new AnswerModel { AnswerId = 276, QuestionId = 69, IsCorrect = false, Answer = "Super Mario Land" },
                new AnswerModel { AnswerId = 277, QuestionId = 70, IsCorrect = true, Answer = "Kart" },
                new AnswerModel { AnswerId = 278, QuestionId = 70, IsCorrect = false, Answer = "Motorcycle" },
                new AnswerModel { AnswerId = 279, QuestionId = 70, IsCorrect = false, Answer = "Bicycle" },
                new AnswerModel { AnswerId = 280, QuestionId = 70, IsCorrect = false, Answer = "ATV" },
                new AnswerModel { AnswerId = 281, QuestionId = 71, IsCorrect = true, Answer = "Yoshi" },
                new AnswerModel { AnswerId = 282, QuestionId = 71, IsCorrect = false, Answer = "Birdo" },
                new AnswerModel { AnswerId = 283, QuestionId = 71, IsCorrect = false, Answer = "Koopa" },
                new AnswerModel { AnswerId = 284, QuestionId = 71, IsCorrect = false, Answer = "Wiggler" },
                new AnswerModel { AnswerId = 285, QuestionId = 72, IsCorrect = true, Answer = "Super Mario Bros. 3" },
                new AnswerModel { AnswerId = 286, QuestionId = 72, IsCorrect = false, Answer = "Super Mario World" },
                new AnswerModel { AnswerId = 287, QuestionId = 72, IsCorrect = false, Answer = "Super Mario 64" },
                new AnswerModel { AnswerId = 288, QuestionId = 72, IsCorrect = false, Answer = "Super Mario Odyssey" },
                new AnswerModel { AnswerId = 289, QuestionId = 73, IsCorrect = true, Answer = "Apples" },
                new AnswerModel { AnswerId = 290, QuestionId = 73, IsCorrect = false, Answer = "Bananas" },
                new AnswerModel { AnswerId = 291, QuestionId = 73, IsCorrect = false, Answer = "Cherries" },
                new AnswerModel { AnswerId = 292, QuestionId = 73, IsCorrect = false, Answer = "Berries" },
                new AnswerModel { AnswerId = 293, QuestionId = 74, IsCorrect = true, Answer = "Super Mario Bros." },
                new AnswerModel { AnswerId = 294, QuestionId = 74, IsCorrect = false, Answer = "Super Mario World" },
                new AnswerModel { AnswerId = 295, QuestionId = 74, IsCorrect = false, Answer = "Super Mario 64" },
                new AnswerModel { AnswerId = 296, QuestionId = 74, IsCorrect = false, Answer = "Super Mario Sunshine" },
                new AnswerModel { AnswerId = 297, QuestionId = 75, IsCorrect = true, Answer = "Donkey Kong" },
                new AnswerModel { AnswerId = 298, QuestionId = 75, IsCorrect = false, Answer = "King K. Rool" },
                new AnswerModel { AnswerId = 299, QuestionId = 75, IsCorrect = false, Answer = "Diddy Kong" },
                new AnswerModel { AnswerId = 300, QuestionId = 75, IsCorrect = false, Answer = "Cranky Kong" },

                // The Legend of Zelda Answers
                new AnswerModel { AnswerId = 301, QuestionId = 76, IsCorrect = true, Answer = "The Minish Cap" },
                new AnswerModel { AnswerId = 302, QuestionId = 76, IsCorrect = false, Answer = "The Wind Cap" },
                new AnswerModel { AnswerId = 303, QuestionId = 76, IsCorrect = false, Answer = "The Phantom Cap" },
                new AnswerModel { AnswerId = 304, QuestionId = 76, IsCorrect = false, Answer = "The Time Cap" },
                new AnswerModel { AnswerId = 305, QuestionId = 77, IsCorrect = true, Answer = "A Link to the Past" },
                new AnswerModel { AnswerId = 306, QuestionId = 77, IsCorrect = false, Answer = "Ocarina of Time" },
                new AnswerModel { AnswerId = 307, QuestionId = 77, IsCorrect = false, Answer = "The Wind Waker" },
                new AnswerModel { AnswerId = 308, QuestionId = 77, IsCorrect = false, Answer = "Twilight Princess" },
                new AnswerModel { AnswerId = 309, QuestionId = 78, IsCorrect = true, Answer = "Master Sword" },
                new AnswerModel { AnswerId = 310, QuestionId = 78, IsCorrect = false, Answer = "Four Sword" },
                new AnswerModel { AnswerId = 311, QuestionId = 78, IsCorrect = false, Answer = "Goddess Sword" },
                new AnswerModel { AnswerId = 312, QuestionId = 78, IsCorrect = false, Answer = "Biggoron's Sword" },
                new AnswerModel { AnswerId = 313, QuestionId = 79, IsCorrect = true, Answer = "Sheik" },
                new AnswerModel { AnswerId = 314, QuestionId = 79, IsCorrect = false, Answer = "Tetra" },
                new AnswerModel { AnswerId = 315, QuestionId = 79, IsCorrect = false, Answer = "Impa" },
                new AnswerModel { AnswerId = 316, QuestionId = 79, IsCorrect = false, Answer = "Zelda" },
                new AnswerModel { AnswerId = 317, QuestionId = 80, IsCorrect = true, Answer = "Master Sword" },
                new AnswerModel { AnswerId = 318, QuestionId = 80, IsCorrect = false, Answer = "Silver Arrows" },
                new AnswerModel { AnswerId = 319, QuestionId = 80, IsCorrect = false, Answer = "Light Arrows" },
                new AnswerModel { AnswerId = 320, QuestionId = 80, IsCorrect = false, Answer = "Bomb Arrows" },
                new AnswerModel { AnswerId = 321, QuestionId = 81, IsCorrect = true, Answer = "Wind Waker" },
                new AnswerModel { AnswerId = 322, QuestionId = 81, IsCorrect = false, Answer = "Ocarina" },
                new AnswerModel { AnswerId = 323, QuestionId = 81, IsCorrect = false, Answer = "Harp" },
                new AnswerModel { AnswerId = 324, QuestionId = 81, IsCorrect = false, Answer = "Flute" },
                new AnswerModel { AnswerId = 325, QuestionId = 82, IsCorrect = true, Answer = "Link's Awakening" },
                new AnswerModel { AnswerId = 326, QuestionId = 82, IsCorrect = false, Answer = "Phantom Hourglass" },
                new AnswerModel { AnswerId = 327, QuestionId = 82, IsCorrect = false, Answer = "Spirit Tracks" },
                new AnswerModel { AnswerId = 328, QuestionId = 82, IsCorrect = false, Answer = "The Wind Waker" },
                new AnswerModel { AnswerId = 329, QuestionId = 83, IsCorrect = true, Answer = "Shigeru Miyamoto" },
                new AnswerModel { AnswerId = 330, QuestionId = 83, IsCorrect = false, Answer = "Eiji Aonuma" },
                new AnswerModel { AnswerId = 331, QuestionId = 83, IsCorrect = false, Answer = "Satoshi Tajiri" },
                new AnswerModel { AnswerId = 332, QuestionId = 83, IsCorrect = false, Answer = "Hideo Kojima" },
                new AnswerModel { AnswerId = 333, QuestionId = 84, IsCorrect = true, Answer = "A sacred relic that bestows great power" },
                new AnswerModel { AnswerId = 334, QuestionId = 84, IsCorrect = false, Answer = "A magical sword" },
                new AnswerModel { AnswerId = 335, QuestionId = 84, IsCorrect = false, Answer = "A shield used by the Hylian Knights" },
                new AnswerModel { AnswerId = 336, QuestionId = 84, IsCorrect = false, Answer = "A charm that protects against evil" },
                new AnswerModel { AnswerId = 337, QuestionId = 85, IsCorrect = true, Answer = "Ocarina of Time" },
                new AnswerModel { AnswerId = 338, QuestionId = 85, IsCorrect = false, Answer = "Master Sword" },
                new AnswerModel { AnswerId = 339, QuestionId = 85, IsCorrect = false, Answer = "Twilight Mirror" },
                new AnswerModel { AnswerId = 340, QuestionId = 85, IsCorrect = false, Answer = "Time Stones" },
                new AnswerModel { AnswerId = 341, QuestionId = 86, IsCorrect = true, Answer = "Ganon" },
                new AnswerModel { AnswerId = 342, QuestionId = 86, IsCorrect = false, Answer = "Vaati" },
                new AnswerModel { AnswerId = 343, QuestionId = 86, IsCorrect = false, Answer = "Dark Link" },
                new AnswerModel { AnswerId = 344, QuestionId = 86, IsCorrect = false, Answer = "Zant" },
                new AnswerModel { AnswerId = 345, QuestionId = 87, IsCorrect = true, Answer = "Transform into different forms" },
                new AnswerModel { AnswerId = 346, QuestionId = 87, IsCorrect = false, Answer = "Travel through time" },
                new AnswerModel { AnswerId = 347, QuestionId = 87, IsCorrect = false, Answer = "Become invisible" },
                new AnswerModel { AnswerId = 348, QuestionId = 87, IsCorrect = false, Answer = "Fly" },
                new AnswerModel { AnswerId = 349, QuestionId = 88, IsCorrect = true, Answer = "Green" },
                new AnswerModel { AnswerId = 350, QuestionId = 88, IsCorrect = false, Answer = "Blue" },
                new AnswerModel { AnswerId = 351, QuestionId = 88, IsCorrect = false, Answer = "Red" },
                new AnswerModel { AnswerId = 352, QuestionId = 88, IsCorrect = false, Answer = "White" },
                new AnswerModel { AnswerId = 353, QuestionId = 89, IsCorrect = true, Answer = "The Legend of Zelda" },
                new AnswerModel { AnswerId = 354, QuestionId = 89, IsCorrect = false, Answer = "Zelda II: The Adventure of Link" },
                new AnswerModel { AnswerId = 355, QuestionId = 89, IsCorrect = false, Answer = "The Legend of Zelda: A Link to the Past" },
                new AnswerModel { AnswerId = 356, QuestionId = 89, IsCorrect = false, Answer = "The Legend of Zelda: Link's Awakening" },
                new AnswerModel { AnswerId = 357, QuestionId = 90, IsCorrect = true, Answer = "Master Sword" },
                new AnswerModel { AnswerId = 358, QuestionId = 90, IsCorrect = false, Answer = "Kokiri Sword" },
                new AnswerModel { AnswerId = 359, QuestionId = 90, IsCorrect = false, Answer = "Biggoron Sword" },
                new AnswerModel { AnswerId = 360, QuestionId = 90, IsCorrect = false, Answer = "Phantom Sword" }
            );

            // QuizQuestions
            modelBuilder.Entity<QuizQuestion>().HasData(
    // World of Warcraft Quiz
    new QuizQuestion { QuizId = 1, QuestionId = 1 },
    new QuizQuestion { QuizId = 1, QuestionId = 2 },
    new QuizQuestion { QuizId = 1, QuestionId = 3 },
    new QuizQuestion { QuizId = 1, QuestionId = 4 },
    new QuizQuestion { QuizId = 1, QuestionId = 5 },
    new QuizQuestion { QuizId = 1, QuestionId = 6 },
    new QuizQuestion { QuizId = 1, QuestionId = 7 },
    new QuizQuestion { QuizId = 1, QuestionId = 8 },
    new QuizQuestion { QuizId = 1, QuestionId = 9 },
    new QuizQuestion { QuizId = 1, QuestionId = 10 },
    new QuizQuestion { QuizId = 1, QuestionId = 11 },
    new QuizQuestion { QuizId = 1, QuestionId = 12 },
    new QuizQuestion { QuizId = 1, QuestionId = 13 },
    new QuizQuestion { QuizId = 1, QuestionId = 14 },
    new QuizQuestion { QuizId = 1, QuestionId = 15 },

    // League of Legends Quiz
    new QuizQuestion { QuizId = 2, QuestionId = 16 },
    new QuizQuestion { QuizId = 2, QuestionId = 17 },
    new QuizQuestion { QuizId = 2, QuestionId = 18 },
    new QuizQuestion { QuizId = 2, QuestionId = 19 },
    new QuizQuestion { QuizId = 2, QuestionId = 20 },
    new QuizQuestion { QuizId = 2, QuestionId = 21 },
    new QuizQuestion { QuizId = 2, QuestionId = 22 },
    new QuizQuestion { QuizId = 2, QuestionId = 23 },
    new QuizQuestion { QuizId = 2, QuestionId = 24 },
    new QuizQuestion { QuizId = 2, QuestionId = 25 },
    new QuizQuestion { QuizId = 2, QuestionId = 26 },
    new QuizQuestion { QuizId = 2, QuestionId = 27 },
    new QuizQuestion { QuizId = 2, QuestionId = 28 },
    new QuizQuestion { QuizId = 2, QuestionId = 29 },
    new QuizQuestion { QuizId = 2, QuestionId = 30 },

    // Pokemon Quiz
    new QuizQuestion { QuizId = 3, QuestionId = 31 },
    new QuizQuestion { QuizId = 3, QuestionId = 32 },
    new QuizQuestion { QuizId = 3, QuestionId = 33 },
    new QuizQuestion { QuizId = 3, QuestionId = 34 },
    new QuizQuestion { QuizId = 3, QuestionId = 35 },
    new QuizQuestion { QuizId = 3, QuestionId = 36 },
    new QuizQuestion { QuizId = 3, QuestionId = 37 },
    new QuizQuestion { QuizId = 3, QuestionId = 38 },
    new QuizQuestion { QuizId = 3, QuestionId = 39 },
    new QuizQuestion { QuizId = 3, QuestionId = 40 },
    new QuizQuestion { QuizId = 3, QuestionId = 41 },
    new QuizQuestion { QuizId = 3, QuestionId = 42 },
    new QuizQuestion { QuizId = 3, QuestionId = 43 },
    new QuizQuestion { QuizId = 3, QuestionId = 44 },
    new QuizQuestion { QuizId = 3, QuestionId = 45 },

    // Counter-Strike Quiz
    new QuizQuestion { QuizId = 4, QuestionId = 46 },
    new QuizQuestion { QuizId = 4, QuestionId = 47 },
    new QuizQuestion { QuizId = 4, QuestionId = 48 },
    new QuizQuestion { QuizId = 4, QuestionId = 49 },
    new QuizQuestion { QuizId = 4, QuestionId = 50 },
    new QuizQuestion { QuizId = 4, QuestionId = 51 },
    new QuizQuestion { QuizId = 4, QuestionId = 52 },
    new QuizQuestion { QuizId = 4, QuestionId = 53 },
    new QuizQuestion { QuizId = 4, QuestionId = 54 },
    new QuizQuestion { QuizId = 4, QuestionId = 55 },
    new QuizQuestion { QuizId = 4, QuestionId = 56 },
    new QuizQuestion { QuizId = 4, QuestionId = 57 },
    new QuizQuestion { QuizId = 4, QuestionId = 58 },
    new QuizQuestion { QuizId = 4, QuestionId = 59 },
    new QuizQuestion { QuizId = 4, QuestionId = 60 },

    // Super Mario Quiz
    new QuizQuestion { QuizId = 5, QuestionId = 61 },
    new QuizQuestion { QuizId = 5, QuestionId = 62 },
    new QuizQuestion { QuizId = 5, QuestionId = 63 },
    new QuizQuestion { QuizId = 5, QuestionId = 64 },
    new QuizQuestion { QuizId = 5, QuestionId = 65 },
    new QuizQuestion { QuizId = 5, QuestionId = 66 },
    new QuizQuestion { QuizId = 5, QuestionId = 67 },
    new QuizQuestion { QuizId = 5, QuestionId = 68 },
    new QuizQuestion { QuizId = 5, QuestionId = 69 },
    new QuizQuestion { QuizId = 5, QuestionId = 70 },
    new QuizQuestion { QuizId = 5, QuestionId = 71 },
    new QuizQuestion { QuizId = 5, QuestionId = 72 },
    new QuizQuestion { QuizId = 5, QuestionId = 73 },
    new QuizQuestion { QuizId = 5, QuestionId = 74 },
    new QuizQuestion { QuizId = 5, QuestionId = 75 },

    // The Legend of Zelda Quiz
    new QuizQuestion { QuizId = 6, QuestionId = 76 },
    new QuizQuestion { QuizId = 6, QuestionId = 77 },
    new QuizQuestion { QuizId = 6, QuestionId = 78 },
    new QuizQuestion { QuizId = 6, QuestionId = 79 },
    new QuizQuestion { QuizId = 6, QuestionId = 80 },
    new QuizQuestion { QuizId = 6, QuestionId = 81 },
    new QuizQuestion { QuizId = 6, QuestionId = 82 },
    new QuizQuestion { QuizId = 6, QuestionId = 83 },
    new QuizQuestion { QuizId = 6, QuestionId = 84 },
    new QuizQuestion { QuizId = 6, QuestionId = 85 },
    new QuizQuestion { QuizId = 6, QuestionId = 86 },
    new QuizQuestion { QuizId = 6, QuestionId = 87 },
    new QuizQuestion { QuizId = 6, QuestionId = 88 },
    new QuizQuestion { QuizId = 6, QuestionId = 89 },
    new QuizQuestion { QuizId = 6, QuestionId = 90 },

    // Mixed Game Quiz (selection from various games)
    new QuizQuestion { QuizId = 7, QuestionId = 1 },
    new QuizQuestion { QuizId = 7, QuestionId = 16 },
    new QuizQuestion { QuizId = 7, QuestionId = 31 },
    new QuizQuestion { QuizId = 7, QuestionId = 46 },
    new QuizQuestion { QuizId = 7, QuestionId = 61 },
    new QuizQuestion { QuizId = 7, QuestionId = 76 },
    new QuizQuestion { QuizId = 7, QuestionId = 3 },
    new QuizQuestion { QuizId = 7, QuestionId = 18 },
    new QuizQuestion { QuizId = 7, QuestionId = 33 },
    new QuizQuestion { QuizId = 7, QuestionId = 48 },
    new QuizQuestion { QuizId = 7, QuestionId = 63 },
    new QuizQuestion { QuizId = 7, QuestionId = 78 },
    new QuizQuestion { QuizId = 7, QuestionId = 5 },
    new QuizQuestion { QuizId = 7, QuestionId = 20 },
    new QuizQuestion { QuizId = 7, QuestionId = 35 }

            );

            // Emails
            modelBuilder.Entity<EmailModel>().HasData(
                new EmailModel { DateLastSent = DateTime.Now, Email = "Maxtharn@gmail.com", EmailId = 1 },
                new EmailModel { DateLastSent = DateTime.Now, Email = "Nckandero@gmail.com", EmailId = 2 },
                new EmailModel { DateLastSent = DateTime.Now, Email = "emil.aberg@live.com", EmailId = 3 },
                new EmailModel { DateLastSent = DateTime.Now, Email = "e.johannesnilsson@gmail.com", EmailId = 4 },
                new EmailModel { DateLastSent = DateTime.Now, Email = "emmzaa1337@gmail.com", EmailId = 5 },
                new EmailModel { DateLastSent = DateTime.Now, Email = "Din@Son.lol", EmailId = 6 },
                new EmailModel { DateLastSent = DateTime.Now, Email = "Din@Kusin.lol", EmailId = 7 },
                new EmailModel { DateLastSent = DateTime.Now, Email = "oscar.sommerfors@gmail.com", EmailId = 8 }
            );

            // QuestionMetaTags
            modelBuilder.Entity<QuestionMetaTag>().HasData(
                new QuestionMetaTag { QuestionId = 1, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 2, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 3, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 4, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 5, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 6, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 7, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 8, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 9, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 10, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 11, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 12, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 13, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 14, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 15, MetaTagId = 1 },
                new QuestionMetaTag { QuestionId = 16, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 17, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 18, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 19, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 20, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 21, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 22, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 23, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 24, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 25, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 26, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 27, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 28, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 29, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 30, MetaTagId = 2 },
                new QuestionMetaTag { QuestionId = 31, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 32, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 33, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 34, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 35, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 36, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 37, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 38, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 39, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 40, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 41, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 42, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 43, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 44, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 45, MetaTagId = 3 },
                new QuestionMetaTag { QuestionId = 46, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 47, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 48, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 49, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 50, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 51, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 52, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 53, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 54, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 55, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 56, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 57, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 58, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 59, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 60, MetaTagId = 4 },
                new QuestionMetaTag { QuestionId = 61, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 62, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 63, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 64, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 65, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 66, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 67, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 68, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 69, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 70, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 71, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 72, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 73, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 74, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 75, MetaTagId = 5 },
                new QuestionMetaTag { QuestionId = 76, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 77, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 78, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 79, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 80, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 81, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 82, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 83, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 84, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 85, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 86, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 87, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 88, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 89, MetaTagId = 6 },
                new QuestionMetaTag { QuestionId = 90, MetaTagId = 6 }
            );
        }
    }
}